openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts Management API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This API allows users to manage their contacts. It provides functionality to create, read, update and delete contacts.
    Contacts can be categorized as work, home, or personal. Users need to authenticate to access their contacts.
tags:
  - name: Contacts
    description: Operations related to contacts management
  - name: Authentication
    description: Operations related to user authentication
servers:
  - url: http://127.0.0.1:3000
  - url: https://nodejs-hw-mongodb-ae8d.onrender.com
paths:
  /contacts/{contactId}:
    $ref: '../src/swagger/paths/contacts/{contactId}/index.yaml'
  /contacts:
    $ref: '../src/swagger/paths/contacts/index.yaml'
  /auth/register:
    $ref: '../src/swagger/paths/auth/register.yaml'
  /auth/login:
    $ref: '../src/swagger/paths/auth/login.yaml'
  /auth/logout:
    $ref: '../src/swagger/paths/auth/logout.yaml'
  /auth/refresh:
    $ref: '../src/swagger/paths/auth/refresh.yaml'
  /auth/send-reset-email:
    $ref: '../src/swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    $ref: '../src/swagger/paths/auth/reset-pwd.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    Unauthorized:
      $ref: ../src/swagger/components/responses/401.yaml
    Forbidden:
      $ref: '../src/swagger/components/responses/403.yaml'
    BadRequest:
      $ref: ../src/swagger/components/responses/400.yaml
    NotFound:
      $ref: '../src/swagger/components/responses/404.yaml'
